"""empty message

Revision ID: 5ab5ffc9e95d
Revises: 73265dd54426
Create Date: 2021-02-22 17:57:29.597771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab5ffc9e95d'
down_revision = '73265dd54426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('msg_text', sa.String(length=400), nullable=True),
    sa.Column('wrote_by', sa.Integer(), nullable=True),
    sa.Column('msg_for', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['msg_for'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wrote_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
