"""empty message

Revision ID: d64dca78ab4b
Revises: 55ae4a411ddd
Create Date: 2021-02-25 20:14:28.382205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64dca78ab4b'
down_revision = '55ae4a411ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('msg', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'msg')
    # ### end Alembic commands ###
