"""empty message

Revision ID: fc5ba16fe22a
Revises: 5ab5ffc9e95d
Create Date: 2021-02-23 21:06:42.053229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5ba16fe22a'
down_revision = '5ab5ffc9e95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('posted_date', sa.Text(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'posted_date')
    # ### end Alembic commands ###
