"""empty message

Revision ID: fc9517990377
Revises: d64dca78ab4b
Create Date: 2021-02-25 20:15:05.617420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc9517990377'
down_revision = 'd64dca78ab4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_msg', sa.String(length=400), nullable=True))
    op.drop_column('notifications', 'msg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('msg', mysql.VARCHAR(length=400), nullable=True))
    op.drop_column('notifications', 'notification_msg')
    # ### end Alembic commands ###
